config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'
Rails.application.routes.draw do
  resources :posts
  get 'static_pages/home'
  mount Sidekiq::Web => '/sidekiq'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  root to: 'pages#home'

  resources :cities

  resources :junctions

  resources :users, only: [:index, :new, :create]

  get '/crossroads', to: "crossroads#show"

  namespace :crossroads do
    resources :roads, only: [:new, :create]
  end

  post "sign_up", to: "users#create"
  get "sign_up", to: "users#new"
  put "account", to: "users#update"
  get "account", to: "users#edit"
  delete "account", to: "users#destroy"

  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  get "login", to: "sessions#new"

  resources :confirmations, only: [:create, :edit, :new], param: :confirmation_token

  resources :passwords, only: [:create, :edit, :new, :update], param: :password_reset_token
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord # rubocop:todo Style/Documentation
  attr_accessor :current_password

  before_save :downcase_email
  before_save :downcase_unconfirmed_email

  CONFIRMATION_TOKEN_EXPIRATION = 10.minutes

  PASSWORD_RESET_TOKEN_EXPIRATION = 10.minutes

  has_secure_password
  has_secure_token :remember_token
  has_many :active_sessions, dependent: :destroy
  validates :name, presence: true, uniqueness: true
  validates :unconfirmed_email, format: { with: URI::MailTo::EMAIL_REGEXP}, presence: true, uniqueness: true

  MAILER_FROM_EMAIL = "no-reply@example.com"

  def confirm!
    if unconfirmed_or_reconfirming?
      if unconfirmed_email.present?
        return false unless update(email: unconfirmed_email, unconfirmed_email: nil)
      end
      update_columns(confirmed_at: Time.current)
    else
      false
    end
  end

  def confirmed?
    confirmed_at.present?
  end

  def generate_confirmation_token
    signed_id expires_in: CONFIRMATION_TOKEN_EXPIRATION, purpose: :confirm_email
  end

  def confirmable_email
    if unconfirmed_email.present?
      unconfirmed_email
    else
      email
    end
  end

  def send_confirmation_email!
    confirmation_token = generate_confirmation_token
    UserMailer.confirmation(self, confirmation_token).deliver_now
  end

  def unconfirmed?
    !confirmed?
  end

  def reconfirming?
    unconfirmed_email.present?
  end

  def unconfirmed_or_reconfirming?
    unconfirmed? || reconfirming?
  end

  def generate_password_reset_token
    signed_id expires_in: PASSWORD_RESET_TOKEN_EXPIRATION, purpose: :reset_password
  end
  ...
  def send_password_reset_email!
    password_reset_token = generate_password_reset_token
    UserMailer.password_reset(self, password_reset_token).deliver_now
  end

  def self.authenticate_by(attributes)
    passwords, identifiers = attributes.to_h.partition do |name, value|
      !has_attribute?(name) && has_attribute?("#{name}_digest")
    end.map(&:to_h)

    raise ArgumentError, "One or more password arguments are required" if passwords.empty?
    raise ArgumentError, "One or more finder arguments are required" if identifiers.empty?
    if (record = find_by(identifiers))
      record if passwords.count { |name, value| record.public_send(:"authenticate_#{name}", value) } == passwords.size
    else
      new(passwords)
      nil
    end
  end

  private

  def downcase_email
    self.email = email.downcase
  end

  def downcase_unconfirmed_email
    return if unconfirmed_email.nil?

    self.unconfirmed_email = unconfirmed_email.downcase
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController # rubocop:todo Style/Documentation
  before_action :authenticate_user!, only: [:edit, :destroy, :update]

  def show
    @user = User.find(params[:id])
  end

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(create_user_params)
    UserMailer.with(user: @user).welcome_email

    # UserInsertionWorker.perform_async(users)

    redirect_to @user

    if @user.save
      @user.send_confirmation_email!
      flash[:notice] = "User created successfully"
      redirect_to users_path, status: :unprocessable_entity
    else
      flash[:alert] = "User not created"
    end
  end

  def destroy
    current_user.destroy
    reset_session
    redirect_to root_path, notice: "Your account has been deleted."
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.authenticate(params[:user][:current_password])
      if @user.update(update_user_params)
        if params[:user][:unconfirmed_email].present?
          @user.send_confirmation_email!
          redirect_to root_path, notice: "Check your email for confirmation instructions."
        else
          redirect_to root_path, notice: "Account updated."
        end
      else
        render :edit, status: :unprocessable_entity
      end
    else
      flash.now[:error] = "Incorrect password"
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def create_user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end

  def update_user_params
    params.require(:user).permit(:current_password, :password, :password_confirmation, :unconfirmed_email)
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper # rubocop:todo Style/Documentation
end

app/views/users/edit.html.erb
<%= simple_form_for @user, url: account_path, method: :put do |form| %>
  <%= render partial: "shared/form_errors", locals: { object: form.object } %>
  <div>
    <%= form.label :email, "Current Email" %>
    <%= form.email_field :email, disabled: true %>
  </div>
  <div>
    <%= form.label :unconfirmed_email, "New Email" %>
    <%= form.input_field :unconfirmed_email %>
  </div>
  <div>
    <%= form.label :password, "Password (leave blank if you don't want to change it)" %>
    <%= form.input_field :password %>
  </div>
  <div>
    <%= form.label :password_confirmation %>
    <%= form.input_field :password_confirmation %>
  </div>
  <hr/>
  <div>
    <%= form.label :current_password, "Current password (we need your current password to confirm your changes)" %>
    <%= form.input_field :current_password, required: true %>
  </div>
  <%= form.button :submit, "Update Account" %>
<% end %>

app/views/users/index.html.erb
<h1>Users</h1>

<%= link_to 'New User', new_user_path %>

<div class="users list">
  <% @users.each do |user|%>
  <li>
    <%= link_to user.name, user %>
  </li>
  <% end %>
</div>

app/views/users/new.html.erb
<%= simple_form_for @user, url: sign_up_path do |form| %>
  <%= render partial: "shared/form_errors", locals: { object: form.object } %>
  <div>
    <%= form.input :email, required: true, label: "Email" %>
  </div>
  <div>
    <%= form.input :password, required: true, label: "Password" %>
  </div>
  <div>
    <%= form.input :password_confirmation, required: true, label: "Confirm Password" %>
  </div>
  <%= form.button :submit, "Sign Up" %>
<% end %>