config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'
Rails.application.routes.draw do
  resources :posts
  get 'static_pages/home'
  mount Sidekiq::Web => '/sidekiq'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  root to: 'pages#home'

  resources :cities

  resources :junctions

  resources :users, only: [:index, :new, :create]

  get '/crossroads', to: "crossroads#show"

  namespace :crossroads do
    resources :roads, only: [:new, :create]
  end

  post "sign_up", to: "users#create"
  get "sign_up", to: "users#new"
  put "account", to: "users#update"
  get "account", to: "users#edit"
  delete "account", to: "users#destroy"

  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  get "login", to: "sessions#new"

  resources :confirmations, only: [:create, :edit, :new], param: :confirmation_token

  resources :passwords, only: [:create, :edit, :new, :update], param: :password_reset_token
end

app/models/active_session.rb
class ActiveSession < ApplicationRecord
  belongs_to :user
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base # rubocop:todo Style/Documentation
  primary_abstract_class
end

app/models/city.rb
# frozen_string_literal: true

class City < ApplicationRecord # rubocop:todo Style/Documentation
  has_many :junctions, dependent: :destroy
  has_many :crossroads, dependent: :destroy

  # belongs_to :country

  validates :name, presence: true
end

app/models/country.rb
# frozen_string_literal: true

class Country < ApplicationRecord
end

app/models/crossroad.rb
class Crossroad < ApplicationRecord
  broadcasts_refreshes

  belongs_to :city

end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :user
end

app/models/junction.rb
# frozen_string_literal: true

class Junction < ApplicationRecord # rubocop:todo Style/Documentation
  include Geocoder

  broadcasts_refreshes
  belongs_to :city
  belongs_to :user

  has_many :posts

  attribute :junction
  attribute :location
  attribute :address

  validates :junction, length: { maximum: 80 }, presence: true

  geocoded_by :address
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :junction

  validates :junction, length: { maximum: 80 }, presence: true
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord # rubocop:todo Style/Documentation
  attr_accessor :current_password

  before_save :downcase_email
  before_save :downcase_unconfirmed_email

  CONFIRMATION_TOKEN_EXPIRATION = 10.minutes

  PASSWORD_RESET_TOKEN_EXPIRATION = 10.minutes

  has_secure_password
  has_secure_token :remember_token
  has_many :active_sessions, dependent: :destroy
  validates :name, presence: true, uniqueness: true
  validates :unconfirmed_email, format: { with: URI::MailTo::EMAIL_REGEXP}, presence: true, uniqueness: true

  MAILER_FROM_EMAIL = "no-reply@example.com"

  def confirm!
    if unconfirmed_or_reconfirming?
      if unconfirmed_email.present?
        return false unless update(email: unconfirmed_email, unconfirmed_email: nil)
      end
      update_columns(confirmed_at: Time.current)
    else
      false
    end
  end

  def confirmed?
    confirmed_at.present?
  end

  def generate_confirmation_token
    signed_id expires_in: CONFIRMATION_TOKEN_EXPIRATION, purpose: :confirm_email
  end

  def confirmable_email
    if unconfirmed_email.present?
      unconfirmed_email
    else
      email
    end
  end

  def send_confirmation_email!
    confirmation_token = generate_confirmation_token
    UserMailer.confirmation(self, confirmation_token).deliver_now
  end

  def unconfirmed?
    !confirmed?
  end

  def reconfirming?
    unconfirmed_email.present?
  end

  def unconfirmed_or_reconfirming?
    unconfirmed? || reconfirming?
  end

  def generate_password_reset_token
    signed_id expires_in: PASSWORD_RESET_TOKEN_EXPIRATION, purpose: :reset_password
  end
  ...
  def send_password_reset_email!
    password_reset_token = generate_password_reset_token
    UserMailer.password_reset(self, password_reset_token).deliver_now
  end

  def self.authenticate_by(attributes)
    passwords, identifiers = attributes.to_h.partition do |name, value|
      !has_attribute?(name) && has_attribute?("#{name}_digest")
    end.map(&:to_h)

    raise ArgumentError, "One or more password arguments are required" if passwords.empty?
    raise ArgumentError, "One or more finder arguments are required" if identifiers.empty?
    if (record = find_by(identifiers))
      record if passwords.count { |name, value| record.public_send(:"authenticate_#{name}", value) } == passwords.size
    else
      new(passwords)
      nil
    end
  end

  private

  def downcase_email
    self.email = email.downcase
  end

  def downcase_unconfirmed_email
    return if unconfirmed_email.nil?

    self.unconfirmed_email = unconfirmed_email.downcase
  end
end

app/controllers/pages_controller.rb
# frozen_string_literal: true

class PagesController < ApplicationController # rubocop:todo Style/Documentation
  def home
    @city = City.find_by(name: 'Metropolis')
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper # rubocop:todo Style/Documentation
end

app/helpers/cities_helper.rb
# frozen_string_literal: true

module CitiesHelper # rubocop:todo Style/Documentation
end

app/helpers/crossroads_helper.rb
module CrossroadsHelper
end

app/helpers/junctions_helper.rb
# frozen_string_literal: true

module JunctionsHelper # rubocop:todo Style/Documentation
end

app/helpers/pages_helper.rb
# frozen_string_literal: true

module PagesHelper # rubocop:todo Style/Documentation
end

app/helpers/passwords_helper.rb
module PasswordsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper # rubocop:todo Style/Documentation
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsJunction</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= render 'shared/header' %>
    <div class="container">
      <%= turbo_frame_tag "modal" %>
      <%= yield %>
      <%= render 'shared/footer' %>
    </div>
  </body>
</html>

app/views/pages/_modal.html.erb
<%= render ModalComponent %>

app/views/pages/home.html.erb
<h1>Homepage</h1>

<h3>Randomly Selected City</h3>
<% random_city = City.all.sample %>

<% if random_city %>
  <p>Name: <%= random_city.name %></p>
  <p>Population: <%= random_city.population %></p>
<% else %>
  <p>No cities found.</p>
<% end %>

<%= line_chart User.group_by_day(:created_at).count %>

<%= link_to "User Sign In", users_path %>

<%= render partial: 'pages/modal' %>

app/views/shared/_flashes.html.erb
<% flash.each do |type, msg| %>
  <div class="alert alert-<%= type %>">
    <%= msg %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer">
  <small>
    <a>Soon to be links</a>
    <a>Another link TBC and added</a>
  </small>
  <nav>
    <ul>
      <li>Link coming soon...</li>
      <li>Link coming soon...</li>
      <li>Link coming soon...</li>
    <ul>
  </nav>
</footer>

app/views/shared/_form_errors.html.erb
<% if object.errors.any? %>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">RailsJunction</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" <%= link_to "Junctions", junctions_path %></a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Sections
          </a>
          <ul class="dropdown-menu">
            <li><a class="nav-link" <%= link_to "New Junction", new_junction_path %></a></li>
            <li><a class="dropdown-item" <%= link_to "All Cities", cities_path %></a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" <%= link_to "Login", login_path %></a></li>
            <li><a class="dropdown-item" <%= link_to "Crossroads", crossroads_path %></a></li>
            <li><a class="dropdown-item" <%= link_to "Users", users_path %></a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled">Unavailable</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" <%= link_to "Posts", posts_path %></a>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>