config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'
Rails.application.routes.draw do
  resources :posts
  get 'static_pages/home'
  mount Sidekiq::Web => '/sidekiq'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  root to: 'pages#home'

  resources :cities

  resources :junctions

  resources :users, only: [:index, :new, :create]

  get '/crossroads', to: "crossroads#show"

  namespace :crossroads do
    resources :roads, only: [:new, :create]
  end

  post "sign_up", to: "users#create"
  get "sign_up", to: "users#new"
  put "account", to: "users#update"
  get "account", to: "users#edit"
  delete "account", to: "users#destroy"

  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  get "login", to: "sessions#new"

  resources :confirmations, only: [:create, :edit, :new], param: :confirmation_token

  resources :passwords, only: [:create, :edit, :new, :update], param: :password_reset_token
end

app/models/junction.rb
# frozen_string_literal: true

class Junction < ApplicationRecord # rubocop:todo Style/Documentation
  include Geocoder

  broadcasts_refreshes
  belongs_to :city
  belongs_to :user

  has_many :posts

  attribute :junction
  attribute :location
  attribute :address

  validates :junction, length: { maximum: 80 }, presence: true

  geocoded_by :address
end

app/controllers/junctions_controller.rb
# frozen_string_literal: true

class JunctionsController < ApplicationController # rubocop:todo Style/Documentation

  def new
    @junction = Junction.new
  end

  def create
    @junction = Junction.new(junction_params)

    if @junction.save
      respond_to do |format|
        format.html { redirect_to junctions_path, notice: 'Junction was successfully created.' }
        format.json { render :show, status: :created, location: @junction }
      end
    else
      format.html { render :new, status: :unprocessable_entity }
      format.json { render json: @junction.errors, status: :unprocessable_entity }
    end
  end

  def show
    @junction = Junction.find(params[:id])
    @posts = @junction.posts
  end

  def index
    @junctions = Junction.all
  end

  private

  def junction_params
    params.require(:junction).permit(:location, :city_id)
  end
end

app/helpers/junctions_helper.rb
# frozen_string_literal: true

module JunctionsHelper # rubocop:todo Style/Documentation
end

app/views/junctions/_form.html.erb
<%= simple_form_for @junction do |f| %>
  <% if @junction.errors.any? %>
    <div style="color: blue">
      <h2><%= pluralize(@junction.errors.count, "error") %> prohibited this new junction from being saved:</h2>

      <ul>
        <% @junction.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= f.label :junction, style: "display: block" %>
  </div>

  <div>
    <%= f.label :name, style: "display: block" %>
  </div>

  <div>
    <%= f.association :city, label_method: :name, value_method: :id, prompt: "Select a city", class: "form-select" %>
  </div>

  <div>
    <%= f.submit %>
  </div>
<% end %>
<h1>Testing</h1>

app/views/junctions/index.html.erb
<h1>Junctions:</h1>
<p>Discover the various junctions in our city:</p>
<div id="junctions">
  <ul>
    <% @junctions.each do |junction| %>
      <li>
        <strong>Junction Name:</strong>
        <%= link_to junction.name || 'Junction will appear soon...', junction_path(junction) %><br>
        <strong>Location:</strong> <%= junction.location %><br>
        <strong>City:</strong> <%= junction.city.name %>
      </li>
    <% end %>
  </ul>
</div>

<%= link_to 'New Junction', new_junction_path, data: { turbo_frame: "modal" } %>

app/views/junctions/new.html.erb
<%= turbo_frame_tag :modal do %>
  <div class="modal">
    <%= render partial: "junctions/form", junction: @junction %>
      <br>
      <div>
        <%= link_to "Cancel", "#", data: {
          controller: "modals",
          action: "modals#close"
        }, class: "cancel-button" %>
      </div>
  </div>
<% end %>
<% link_to "Home", root_path %>

app/views/junctions/show.html.erb
<h1>Junction Details:</h1>
<p>Explore the details of this junction:</p>

<div id="junction-details">
  <strong>Junction Name:</strong> <%= @junction.name %><br>
  <strong>Location:</strong> <%= @junction.location %><br>
  <strong>City:</strong> <%= @junction.city.name %>
</div>

<%= link_to 'New Junction', new_junction_path %>